config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_keymap.cson:
    src: macos/inkdrop/keymap.cson
    dst: ~/Library/Application Support/inkdrop/keymap.cson
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  f_editorconfig:
    src: editorconfig
    dst: ~/.editorconfig
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    instignore:
    - .zhistory
    - .zsh_history
    - .zcompdump
    cmpignore:
    - .zhistory
    - .zsh_history
    - .zcompdump
    upignore:
    - .zhistory
    - .zsh_history
    - .zcompdump
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
  f_taskrc:
    src: taskrc
    dst: ~/.taskrc
  f_vsc_mac:
    src: Code/User/settings.json
    dst: ~/Library/Application Support/Code/User/settings.json
  f_tmux.conf:
    src: config/tmux/tmux.conf
    dst: ~/.config/tmux/tmux.conf
profiles:
  Charlies-MacBook-Pro.local:
    dotfiles:
    - f_keymap.cson
    - d_nvim
    - d_alacritty
    - f_editorconfig
    - d_zsh
    - f_zshenv
    - f_ideavimrc
    - f_taskrc
    - f_vsc_mac
    - f_tmux.conf
