config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_macos_inkdrop_keymap.cson:
    src: macos/inkdrop/keymap.cson
    dst: ~/Library/Application Support/inkdrop/keymap.cson
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    instignore:
      - .netrwhist
    cmpignore:
      - .netrwhist
    upignore:
      - .netrwhist
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  f_editorconfig:
    src: editorconfig
    dst: ~/.editorconfig
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    instignore:
      - .zhistory
      - .zsh_history
      - .zsh_sessions
      - .zcompdump
    cmpignore:
      - .zhistory
      - .zsh_history
      - .zsh_sessions
      - .zcompdump
    upignore:
      - .zhistory
      - .zsh_history
      - .zsh_sessions
      - .zcompdump
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
  f_taskrc:
    src: taskrc
    dst: ~/.taskrc
  f_macos_vsc:
    src: macos/Code/User/settings.json
    dst: ~/Library/Application Support/Code/User/settings.json
  f_tmux.conf:
    src: config/tmux/tmux.conf
    dst: ~/.config/tmux/tmux.conf
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_home_gitconfig.local:
    src: home/gitconfig.local
    dst: ~/.gitconfig.local
  f_mangroup_gitconfig.local:
    src: mangroup/gitconfig.local
    dst: ~/.gitconfig.local
  f_inputrc:
    src: inputrc
    dst: ~/.inputrc
  d_ipython_profile_default_startup:
    src: ipython/profile_default/startup
    dst: ~/.ipython/profile_default/startup
    instignore:
      - 00-private-setup.py
      - 99-private-setup.py
    cmpignore:
      - 00-private-setup.py
      - 99-private-setup.py
    upignore:
      - 00-private-setup.py
      - 99-private-setup.py
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_mangroup_wsl_bashrc:
    src: mangroup/wsl/bashrc
    dst: ~/.bashrc
  d_karabiner:
    src: config/karabiner
    dst: ~/.config/karabiner
    chmod: '700'
    instignore:
    - automatic_backups
    cmpignore:
    - automatic_backups
    upignore:
    - automatic_backups
profiles:
  Charlies-MacBook-Pro.local:
    dotfiles:
      - f_macos_inkdrop_keymap.cson
      - d_nvim
      - d_alacritty
      - f_editorconfig
      - d_zsh
      - f_zshenv
      - f_ideavimrc
      - f_taskrc
      - f_macos_vsc
      - f_tmux.conf
      - f_gitconfig
      - f_home_gitconfig.local
      - f_inputrc
      - d_ipython_profile_default_startup
      - f_vimrc
      - d_karabiner
  Charlies-MacBook-Pro-2.local:
    dotfiles:
      - f_macos_inkdrop_keymap.cson
      - d_nvim
      - d_alacritty
      - f_editorconfig
      - d_zsh
      - f_zshenv
      - f_ideavimrc
      - f_taskrc
      - f_macos_vsc
      - f_tmux.conf
      - f_gitconfig
      - f_home_gitconfig.local
      - f_inputrc
      - d_ipython_profile_default_startup
      - f_vimrc
      - d_karabiner
  ManGroupWindowsLaptop:
    dotfiles:
      - f_gitconfig
      - f_mangroup_gitconfig.local
      - f_ideavimrc
      - f_inputrc
      - d_ipython_profile_default_startup
      - f_vimrc
  ManGroupWSLLaptop:
    dotfiles:
      - d_nvim
      - f_editorconfig
      - f_ideavimrc
      - f_inputrc
      - d_ipython_profile_default_startup
      - f_gitconfig
      - f_mangroup_gitconfig.local
      - f_tmux.conf
      - f_vimrc
      - f_mangroup_wsl_bashrc
  ManGroupLinuxHeadnode:
    dotfiles:
      - f_gitconfig
      - f_mangroup_gitconfig.local
      - f_inputrc
      - d_nvim
      - d_ipython_profile_default_startup
      - f_vimrc
dynvariables:
  home: echo $HOME
